# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION

version-template: $MAJOR.$MINOR.$PATCH

categories:
  - title: 💥 Breaking changes
    labels: 
      - breaking
  - title: 🚨 Removed
    label: removed
  - title: 🎉 Major features and improvements
    labels:
      - major-enhancement
      - major
  - title: 🎉 minor improvements
    labels:
      - minor-enhancement
      - minor
  - title: 🐛 Major bug fixes
    labels:
      - major-bug
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
      - rfe
  - title: 🐛 Bug fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 👷 Changes for plugin developers
    labels:
      - developer 
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 📝 Documentation updates
    label: documentation
  - title: 👻 Maintenance
    labels: 
      - chore
      - internal
  - title: 🚦 Tests
    labels: 
      - test
      - tests
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  <!-- Optional: add a release summary here -->
  ## Changes

  $CHANGES

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'